### ISSUE TITLE
Не могу установить.

### ISSUE THREAD

**Issue by Doncode** [zadarma/user-api-v1#1]
composer require "zadarma/user-api-v1"
  [InvalidArgumentException]
  Could not find package zadarma/user-api-v1 at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

Класс не устанавливается через composer. Пожалуйста добавьте тег с версией

**Comment by zadarma** [comment]
Добрый день,

Добавили номер версии, попробуйте сейчас.

С уважением,
Дмитрий

2015-09-19 19:08 GMT+02:00 Alex <notifications@github.com>:
