### ISSUE TITLE
API Error: SSL connect error

### ISSUE THREAD

**Issue by hostbox2** [zadarma/user-api-v1#11]
При обращении к API через библиотеку "zadarma/user-api-v1": "v1.1.4" с рабочего сервера 
получаю такую ошибку: "Error: SSL connect error"

На хосте, откуда исходит запрос установлен и корректно работает SSL сертификат от Let's encrypt. Данные сертификаты поддерживаются всеми основными современными браузерами и отвечают требованиям безопасности. Есть поддержка TLS выше 1.0

Сами результаты теста вы можете посмотреть здесь: 
https://www.ssllabs.com/ssltest/analyze.html?d=order.steelcam.org

Специалист поддержки отвечает, что API zadarma требует поддержки протокола SSL2 и SSL3, а также выше TLS 1.0. Однако сам хост api.zadarma.com не поддерживает протоколы SSL2 и SSL3, но требует их у других (отчет: https://www.ssllabs.com/ssltest/analyze.html?d=api.zadarma.com)

Подскажите, почему так происходит? Может стоит изменить правила обработки API запросов?

**Comment by zadarma** [comment]
Для работы с API Zadarma  на вашем сервере должна быть корректно настроена поддержка работы по протоколам TLSv1.1 или TLSv1.2

**Comment by hostbox2** [comment]
Сейчас настроено корректно, имеется поддержка TLS 1.1 и 1.2. Проблема сохраняется

**Comment by zadarma** [comment]
API работает корректно, просьба обратиться в https://my.zadarma.com/tickets/
Для решения вашей проблемы

**Comment by hostbox2** [comment]
> API работает корректно, просьба обратиться в https://my.zadarma.com/tickets/
> Для решения вашей проблемы

Уже обратился. Там утверждают тоже самое, но это не помогает мне решить конкретную проблему.
