### ISSUE TITLE
caller_id ignored in sendSms

### ISSUE THREAD

**Issue by mlan** [zadarma/user-api-v1#13]
Dear Zadarma,

Up until April 2020, I was able to send SMS with the caller_id value being respected.

But, now in May 2020, the caller_id value is ignored and SMS is sent "From: zadarma.com".

Please, please, help me fix this issue.

Kind regards, Martin

**Comment by zadarma** [comment]
It’s not an API issue. Please describe your problem in ticket from personal account.

**Comment by mlan** [comment]
Dear Zadarma,

Yes, is most likely not an issue with the client side of the API. I'm have an active ticket with the Zadarma support team, but the only answer I get is that Zadarma does not guarantee that the caller_id value is being honored, and I just have to live with it not working. 

What I see on my side is (not actual phone numbers):
string(67) "caller_id=12025550183&message=Outgoing+message+6&number=12025550160"
string(63) "{"status":"success","messages":1,"cost":0.052,"currency":"EUR"}"

Perhaps me posting here was an act out of desperation.

Do you think there is a chance I can get some help by posting (in English) on the Russian forum.zadarma.com?

Kind regards, Martin
