### ISSUE TITLE
Уязвимость при уведомлении о входящих звонках

### ISSUE THREAD

**Issue by sevkin** [zadarma/user-api-v1#2]
Я так понимаю уведомление о входящем вызове никак не защищено и его может вызвать (зная урл) кто угодно?

Почему бы не сделать точно такую же защиту как при вызове методов, только с подписью уже на вашей стороне?

```php
$header = 'Authorization: ' . $userKey . ':' . $sign;
```

Или, если это есть, почему бы в примере **examples/callinfo_callback.php** это не изобразить?

**Comment by zadarma** [comment]
Добавили в код эту проверку. И еще можно закрыть все входящие запросы по IP сервиса (тоже есть в примере).
