### ISSUE TITLE
Полноценный SDK

### ISSUE THREAD

**Issue by jurchiks** [zadarma/user-api-v1#4]
Имеются ли планы создать для вашего API полноценный SDK, как тут: https://github.com/Sharoff45/zadarma-api
?
Данный пример, к сожалению, не полностью совпадает с вашей API документацией (отсутствует методы `/v1/tariff/`, `/v1/sip/<SIP>/status/`, `/v1/direct_numbers/`, `/v1/sim/`, `/v1/pbx/internal/<PBXSIP>/status/`, и `/v1/pbx/record/request/`), к тому же он не официальный.

Ваша "библиотека" практически заставляет каждому пользователю вашего API самому писать вот такую абстракцию, если хочется хоть немного удобства (например, нормализация номера телефона).

**Comment by Solverin** [comment]
Так же интересует этот вопрос.

**Comment by a2nt** [comment]
Видимо программистам просто не платят - работают за еду

**Comment by zadarma** [comment]
Вы можете использовать методы нового класса /Zadarma_API/Api для этих целей.
